server:
  port: 7001
eureka:
  client:
    #是否自己注册自己
    register-with-eureka: true
    #是否拉取信息
    fetch-registry: true
    service-url:
      #eureka 端口
      defaultZone: http://eureka2.com:7002/eureka/
  instance:
    hostname: eureka1.com
spring:
  application:
    name: eureka
