server:
  port: 7002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/
  instance:
    hostname: eureka2.com
spring:
  application:
    name: eureka
